image: "python:3.9.5"

before_script:
  - python3 --version
  - pip3 install -r requirements.txt

stages:
  - Linting

flake8:
  stage: Linting
  tags:
    - ubuntu
    - linux
  script: 
    - flake8 --max-line-length=120 --ignore=F401 *.py

pylint:
  stage: Linting
  allow_failure: true
  script:
    - pylint -d C0301 *.py
  tags:
    - ubuntu
    - linux
